import type { Metadata } from 'next';
import '@/styles/globals.css';
import { Footer, Navbar } from '@/components/layout';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: {
		icon: '/favicon.ico',
	},
};

/**
 * The root layout of the app, which wraps the entire app with
 * the navbar and footer.
 *
 * This layout is shared by all pages.
 *
 * @param children The children elements to render inside the layout.
 * @returns A JSX element representing the root layout.
 */
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
